- name: Run powershell script
  hosts: all 
  gather_facts: false
  
  vars_files:
     - copy_variable.yml
     
  tasks:
    - name: Run powershell script
      win_shell: |
           powershell
           cd C:\Users\Administrator\Downloads
           echo y | pscp -r  -pw "{{ password  }}" C:\Users\Administrator\Downloads\result.html\* {{ username }}@{{ ip_add }}:C:\Users\Administrator\Downloads
