---
- name: Running Docker
  hosts: all
  become: true
  gather_facts: false
  tasks:

    - name: create container jmeter

      docker_container:
        name: jmeter
        image: harishpallapu/jmeter-3i:latest
        state: started
        file:
           path: /jmeter/bin/project
           owner: root
           group: root
           mode: 0755
           recurse: yes
           state: directory
        git:
           repo: https://github.com/Poornateja2509/NRTC_JMeter.git 
           dest: /jmeter/bin/project
        



   
